### PR TITLE
cdfutils is now on PyPI

### PR DESCRIPTION
**Pull request by cdfarrow**

### CODE REVIEW

**Comment by cdfarrow** [comment]
Merge changes to requirements.txt and .gitignore from Master to Develop

**Comment by rmlockwood** [comment]
Does this mean git is no longer required to get dependencies?

**Comment by cdfarrow** [comment]
Yes it does! So you can remove git from your installation steps. :-)

**Comment by rmlockwood** [comment]
Wonderful! Thanks so much!

**Pull request merged**
